// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by Makefile during build
// To regenerate: make gen-buildinfo

import Foundation

/// Build-time information injected by Makefile
public struct ArcaBuildInfo {
    /// Git commit hash at build time
    public static let gitCommit = "5b5cdc3"

    /// ISO8601 timestamp of build
    public static let buildTime = "2025-12-17T17:33:09Z"
}
